"""
Rule-based reference implementation of `onboarding-agent`.
Swap for orchestrator/bob_backend.py + bob-agents/onboarding-agent.md
during the hackathon — that version reads full repo context via Bob and
writes much richer prose. This version proves the pipeline (including
reuse of compliance-agent's and diff-analyst's outputs) works end to end.
"""
import os
import json

from .. import gitutil


def run(repo_root, sample_project_path="sample-project"):
    src_dir = os.path.join(repo_root, sample_project_path)
    agents_md = _read(os.path.join(src_dir, "AGENTS.md"))
    setup_checklist = _read_json(os.path.join(repo_root, "setup-checklist.json"))
    risk_scan = _build_risk_scan(repo_root, src_dir)

    safest = sorted(risk_scan.items(), key=lambda kv: kv[1])[:3]

    brief = f"""# Onboarding Brief — Tasks API

_Generated by onboarding-agent. Reuses compliance-agent's setup checklist and
diff-analyst's file-churn risk scan instead of recomputing them — this reuse
is the core "shared repo-intelligence engine" idea behind RepoPilot._

## 1. Architecture map

{_extract_section(agents_md, "## Project", "## Structure")}

```mermaid
graph TD
  Client -->|HTTP| Routes[app/routes.py]
  Routes --> DB[app/db.py - in-memory store]
  Tests[tests/test_tasks.py] -.->|exercises| Routes
```

## 2. Where things live

{_extract_section(agents_md, "## Where things live", "## Known risk areas") or "See AGENTS.md."}

## 3. Domain glossary

- **Task** — a unit of work with a title and a completion flag.
- **TASKS_MAX_LIMIT** — env var capping how many tasks `GET /tasks` returns.
- **Response contract** — the fixed JSON shape returned for a task, defined
  once in `_serialize()`.

## 4. Day 0 setup checklist

{_render_setup_checklist(setup_checklist)}

## 5. Safest first tasks (lowest historical churn = lowest risk)

{_render_safest(safest)}

## 6. Self-check quiz

{QUIZ}
"""
    out_path = os.path.join(repo_root, "onboarding-brief.md")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(brief)
    return out_path


def _build_risk_scan(repo_root, src_dir):
    scan = {}
    for root, _, names in os.walk(src_dir):
        for name in names:
            if name.endswith(".py"):
                rel = os.path.relpath(os.path.join(root, name), repo_root)
                scan[rel] = gitutil.churn(repo_root, rel)
    out_path = os.path.join(repo_root, "risk-scan.json")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(scan, fh, indent=2)
    return scan


def _extract_section(text, start_marker, end_marker):
    if start_marker not in text:
        return ""
    start = text.index(start_marker) + len(start_marker)
    end = text.index(end_marker, start) if end_marker in text[start:] else len(text)
    return text[start:end].strip()


def _render_setup_checklist(checklist):
    if not checklist:
        return "- (compliance-agent has not run yet — run PR mode first to populate this)"
    lines = []
    for key, status in checklist.items():
        mark = "x" if status == "PASS" else " "
        lines.append(f"- [{mark}] {key.replace('_', ' ')} — {status}")
    return "\n".join(lines)


def _render_safest(safest):
    lines = []
    for i, (path, churn_score) in enumerate(safest, start=1):
        lines.append(f"{i}. `{path}` — churn score {churn_score} (fewer historical changes = safer to learn on)")
    return "\n".join(lines) if lines else "Not enough git history yet."


QUIZ = """
1. Which file defines the public JSON shape returned for a task?
   a) app/db.py  b) app/routes.py  c) tests/test_tasks.py
   **Answer: b** — `_serialize()` in routes.py is the single source of truth for the response contract.

2. Where would you add a new environment variable?
   a) Just read it with os.environ  b) .env.example and README.md  c) CHANGELOG.md only
   **Answer: b** — undocumented env vars are exactly what compliance-agent flags as a release blocker.

3. What does db.reset() do and when is it called?
   a) Clears all tasks; called in test setUp()  b) Resets the Flask app  c) Nothing, it's unused
   **Answer: a** — keeps each test isolated from previous test state.

4. If you rename a field in a task's JSON response, what should you also do?
   a) Nothing  b) Bump version + update CHANGELOG.md + consider an alias  c) Just tell your team verbally
   **Answer: b** — this is the #1 breaking-change pattern diff-analyst watches for.

5. Which file would you touch to change how tasks are stored?
   a) app/routes.py  b) app/db.py  c) run.py
   **Answer: b**
"""


def _read(path):
    if not os.path.isfile(path):
        return ""
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _read_json(path):
    if not os.path.isfile(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


if __name__ == "__main__":
    import sys
    repo_root = sys.argv[1]
    print("Wrote:", run(repo_root))
